# Generated by Django 4.1.2 on 2022-10-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_converted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
