# Generated by Django 4.1.2 on 2022-10-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_category_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
